src/blogs/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

from rest_framework_jwt.views import obtain_jwt_token


from accounts.views import (login_view, register_view, logout_view) 




urlpatterns = [
    url(r'^admin/', admin.site.urls,),
    url(r'^comments/', include('comments.urls', namespace='comments') ),
    url(r'^login/', login_view, name='login'),
    url(r'^register/', register_view, name='register'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^api/token/auth/', obtain_jwt_token),
    url(r'^api/accounts/', include('accounts.api.urls', namespace='accounts-api') ),
    url(r'^api/comments/', include('comments.api.urls', namespace='comments-api') ),
    url(r'^api/posts/', include('posts.api.urls', namespace='posts-api') ),
    url(r'^', include('posts.urls', namespace='posts') ),


]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

src/posts/api/urls.py
from django.conf.urls import url

from .views import (
    PostCreateAPIView,
    PostUpdateAPIView,
    PostDeleteAPIView,
    PostDetailAPIView,
    PostListAPIView,
    )

urlpatterns = [
    url(r'^create/$', PostCreateAPIView.as_view(), name='create'),
    url(r'^(?P<slug>[\w-]+)/delete/$', PostDeleteAPIView.as_view(), name='delete'),
    url(r'^(?P<slug>[\w-]+)/$', PostDetailAPIView.as_view(), name='detail'),
    url(r'^$', PostListAPIView.as_view(), name='list'),
    url(r'^(?P<slug>[\w-]+)/update/$', PostUpdateAPIView.as_view(), name='update'),
]

src/posts/urls.py
from django.conf.urls import url

from .views import (
	post_list,
	post_detail,
	post_create,
	post_update,
	post_delete,
)

urlpatterns = [
    url(r'^$', post_list, name='list'),
    url(r'^create/$', post_create, name='create'),
    url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', post_update, name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', post_delete, name='delete'),
]

src/posts/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.conf import settings
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.contrib.contenttypes.models import ContentType



from markdown_deux import markdown


from comments.models import Comment
from .utils import get_read_time


class PostManager(models.Manager):
    def active(self):
        return super(PostManager, self)\
                        .filter(draft=False)\
                        .filter(publish__lte=timezone.now())


# Create your models here.
def upload_location(instance, filename):
	return "%s/%s" %(instance.id, filename)


class Post (models.Model):
    title = models.CharField(max_length=120)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    slug = models.SlugField(unique=True)
    image = models.ImageField(
    	upload_to=upload_location, 
        null=True, blank=True,
    	width_field="width_field", 
    	height_field="height_field"
	)
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    content = models.TextField()
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False, auto_now_add=False)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    read_time = models.IntegerField(blank=True, null=True)

    objects = PostManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('posts:detail', kwargs={'slug': self.slug})

    def get_api_url(self):
        return reverse('posts-api:detail', kwargs={'slug': self.slug})

    def get_markdown(self):
        return mark_safe(markdown(self.content))

    @property
    def comments(self):
        return Comment.objects.filter_by_instance(self)

    @property
    def get_content_type(self):
        return ContentType.objects.get_for_model(self.__class__)

    class Meta:
    	ordering = ['-timestamp', '-updated']

def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)
    if instance.content:
        html_text = instance.get_markdown()
        instance.read_time = get_read_time(html_text)



pre_save.connect(pre_save_post_receiver, sender=Post)

src/posts/forms.py
from django import forms

from pagedown.widgets import PagedownWidget

from .models import Post

class PostForm(forms.ModelForm):
	content = forms.CharField(widget=PagedownWidget(show_preview=False))
	publish = forms.DateField(widget=forms.SelectDateWidget)
	class Meta:
		model = Post
		fields = [
			'title',
			'image',
			'content',
			'draft', 
			'publish',
		]

src/posts/api/views.py
from django.db.models import Q


from rest_framework.generics import (
        DestroyAPIView,
        ListAPIView,
        RetrieveAPIView,
        RetrieveUpdateAPIView,
        CreateAPIView,
        )
from rest_framework.filters import (
        SearchFilter,
        OrderingFilter,
        )
from rest_framework.pagination import (
        LimitOffsetPagination,
        PageNumberPagination,
        )
from rest_framework.permissions import (
        AllowAny,
        IsAdminUser,
        IsAuthenticated,
        IsAuthenticatedOrReadOnly,
        )


from posts.models import Post 
from .pagination import PostPageNumberPagination
from .permissions import IsOwnerOrReadOnly
from .serializers import (
        PostListSerializer,
        PostDetailSerializer, 
        PostCreateUpdateSerializer,
        )




class PostCreateAPIView(CreateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostCreateUpdateSerializer

    def perfom_create(self, serializer):
        serializer.save(user=self.request.user)


class PostUpdateAPIView(RetrieveUpdateAPIView):
    queryset = Post.objects.all()
    serializer_class = PostCreateUpdateSerializer
    permission_classes = [IsOwnerOrReadOnly, ]
    lookup_field = 'slug'

    def perfom_update(self, serializer):
        serializer.save(user=self.request.user)


class PostDeleteAPIView(DestroyAPIView):
    queryset = Post.objects.all()
    serializer_class = PostDetailSerializer
    permission_classes = [IsOwnerOrReadOnly, ]
    lookup_field = 'slug'


class PostDetailAPIView(RetrieveAPIView):
    queryset = Post.objects.all()
    serializer_class = PostDetailSerializer
    lookup_field = 'slug'


class PostListAPIView(ListAPIView):
    serializer_class = PostListSerializer
    filter_backend = [SearchFilter,]
    search_fields = ['title', 'content', 'user__first_name' ]
    pagination_class = PostPageNumberPagination
    permission_classes = [AllowAny] 


    def get_queryset(self, *args, **kwargs):
        queryset_list = Post.objects.all()
        query = self.request.GET.get('q')
        if query:
            queryset_list = queryset_list.filter(
                            Q(title__icontains=query)|
                            Q(content__icontains=query)|
                            Q(user__first_name__icontains=query)|
                            Q(user__last_name__icontains=query)
                            ).distinct()
        return queryset_list

src/posts/views.py
from urllib.parse import quote_plus


from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.http import  HttpResponseRedirect, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone



from .forms import PostForm
from .models import Post
from .utils import get_read_time
from comments.models import Comment
from comments.forms import CommentForm



# Create your views here.
def post_create(request):
    if not request.user.is_superuser or not request.user.is_staff:
        raise Http404
    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        messages.success(request, "Instance was saved")
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {
        'form': form
    }
    return render(request, 'post_form.html', context)


def post_detail(request, slug=None):
    instance = get_object_or_404(Post, slug=slug)

    if instance.draft or instance.publish > timezone.now().date():
        if not request.user.is_superuser or not request.user.is_staff:
            raise Http404
    initial_data={
        'content_type' : instance.get_content_type,
        'object_id' : instance.id,
    }
    form = CommentForm(request.POST or None, initial=initial_data)
    if form.is_valid() and request.user.is_authenticated():
        c_type = form.cleaned_data.get('content_type')
        content_type = ContentType.objects.get(model=c_type)
        object_id = form.cleaned_data.get('object_id')
        content = form.cleaned_data.get('content')
        parent_obj = None;
        try:
            parent_id = int(request.POST.get('parent_id'))
        except:
            parent_id = None
        if parent_id:
            parent_qs = Comment.objects.filter(id=parent_id)
            if parent_qs.exists() and parent_qs.count() == 1:
                parent_obj = parent_qs.first()
        new_comment, created = Comment.objects.get_or_create(
                        user = request.user,
                        content_type = content_type,
                        content = content,
                        object_id = object_id,
                        parent = parent_obj,
                    )
        return HttpResponseRedirect(new_comment.content_object.get_absolute_url())
    comments = instance.comments
    context = {
        'instance' : instance,
        'comments' : comments,
        'comment_form' : form,
    }
    return render(request, 'post_detail.html', context)

def post_list(request):
    today = timezone.now().date()
    if request.user.is_staff or request.user.is_superuser:
        queryset_list = Post.objects.all()
    else:
        queryset_list = Post.objects.active()
    query = request.GET.get('q')
    if query:
        queryset_list = queryset_list.filter(
                        Q(title__icontains=query)|
                        Q(content__icontains=query)|
                        Q(user__first_name__icontains=query)|
                        Q(user__last_name__icontains=query)
                        ).distinct()
    paginator = Paginator(queryset_list, 5) # Show 25 contacts per page

    page = request.GET.get('page')
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        queryset = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        queryset = paginator.page(paginator.num_pages)
    context = {
            "object_list": queryset,
            "today": today,
    }
    return render(request, 'post_list.html', context)



def post_update(request, slug=None):
    if not request.user.is_superuser or not request.user.is_staff:
        raise Http404
    instance = get_object_or_404(Post, slug=slug)
    form = PostForm(
        request.POST or None, 
        request.FILES or None, 
        instance=instance
    )
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, "Instance was saved")
        return HttpResponseRedirect(instance.get_absolute_url())

    context = {
        'title' : instance.title,
        'instance' : instance,
        'form' : form,
    }
    return render(request, 'post_form.html', context)

def post_delete(request, slug=None):
    if not request.user.is_superuser or not request.user.is_staff:
        raise Http404
    instance = get_object_or_404(Post, slug=slug)
    instance.delete()
    messages.success(request, 'Deleted')
    return redirect('posts:list')

src/templates/base.html
{% load staticfiles %}
<html>
<head>
<title>{% block head_title %}RVS-Blog-Django{% endblock head_title %}
</title>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
<style type="text/css">
	{% block style %}{% endblock style %}
</style>


{% block head_extra %}{% endblock head_extra %}

</head>

<body>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.9";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>


<div class="container">
<ol class="breadcrumb">
    <li><a href="{% url 'posts:list' %}">Posts</a></li>
    {% if request.user.is_superuser or request.user.is_staff %}
    <li><a href="{% url 'posts:create' %}">Create new post</a></li>
    <li><a href="{% url 'admin:index' %}">Admin</a></li>
    {% endif %}

    {% if not request.user.is_authenticated %}
    <li class="pull-right"><a href="{% url 'register' %}">Register</a></li>
    <li class="pull-right"><a href="{% url 'login' %}">Login</a></li>
    {% else %}
    <li class="pull-right"><a href="{% url 'logout' %}">Logout</a></li>
    {% endif %}
</ol>
	{% block content %}{% endblock content %}
</div>


 <!-- Latest compiled and minified JavaScript -->

<script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>


<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.6/marked.min.js"></script>

<script type="text/javascript">
	$(document).ready(function(){
		$(".content-markdown").each(function(){
		var content = $(this).text()
		var markedContent = marked(content)
		$(this).html(markedContent)
		})
	}) 

	$(document).ready(function(){
		$(".post-detail-item img").each(function(){
		$(this).addClass("img-responsive")
		})
	}) 
		
	
// for form.html
	$(document).ready(function(){
		$("#preview-title").text($("#id_title").val())
		$("#preview-content").html(marked($("#id_content").val()))
		$("#preview-content img").addClass("img-responsive")
	}) 

	$("#id_title").keyup(function(){
		$("#preview-title").text($(this).val())
	})

	$("#id_content").keyup(function(){
		$("#preview-content").html(marked($(this).val()))
		$("#preview-content img").addClass("img-responsive")
	})

    $(".comment-reply-btn").click(function(event){
        event.preventDefault();
        $(this).parent().next(".comment-reply").fadeToggle();
    })


</script>
</body>
</html>

src/templates/comment_thread.html
{% extends "base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}

{% block head_title %}
    {{ instance.title }} |  {{ block.super }}
{% endblock head_title %}

{% block content %}

    <div class="col-xs-12 col-xs-offset-0 col-sm-9 col-sm-offset-1 col-md-6 col-md-offset-3 post-detail-item">
    <h1>Comment Thread</h1>
        <p class="mb-0">{{ comment.content }}</p>
        <footer class="blockquote-footer">{{ comment.user }} | {{ comment.timestamp|timesince }} ago | {% if comment.children.count > 1 %} {{ comment.children.count }} comments | {% endif %} {% if comment.children.count == 1 %} 1 comment | {% endif %}
        {% if comment.user == request.user %}
        <a href="{{ comment.get_delete_url }}" >Delete a comment</a>
        {% endif %}
        </footer>
        <hr>
        {% for child_comment in comment.children %}
            <blockquote class="blockquote">
              <p class="mb-0">{{ child_comment.content }}</p>
              <footer class="blockquote-footer">{{ child_comment.user }} | {{ child_comment.timestamp|timesince }} ago
              {% if child_comment.user == request.user %}
                <a href="{{ child_comment.get_delete_url }}" > | Delete a comment</a>
                {% endif %}</footer>
            </blockquote>
        {% endfor %}
        <form method="POST" action="">
            {% csrf_token %}
            {{ comment_form|crispy }}
            <input type="hidden" name="parent_id" value="{{ comment.id }}" >
            <input type="submit" value="Reply" class="btn btn-default">
            <a href="{{ comment.content_object.get_absolute_url }}" class="btn btn-default">Return</a>

        </form>
        
    </div>
{% endblock content %}

src/templates/confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_title %}FORM | {{ block.super }}{% endblock head_title %}
{% block head_extra %}{{ form.media }}{% endblock head_extra %}
    
{% block content %} 

<div class="col-md-6 col-md-offset-3">

<h1>Confirm delete</h1>

<form method="POST" action="">
{% csrf_token %}
<p>Do you want to delete the comment "{{ comment.content }}"?</p>    
<input type="submit" class="btn btn-warning"  value="Confirm">
<a href="{{ comment.get_absolute_url }}" class="btn btn-default">Cancel</a>
</form>
</div>

{% endblock content %}

src/templates/form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %} 

<div class="col-xs-8 col-xs-offset-2 col-sm-5 col-sm-offset-4 col-md-3 col-md-offset-3">

<h1>{{ title }}</h1>
<form method="POST" action="" enctype="multipart/form-data">
{% csrf_token %}    
{{ form|crispy }}
<input type="submit" class="btn btn-default"  value="{{ title }}">
</form>



{% endblock content %}

src/templates/messages_display.html
{% if messages %}
	<ul class="messages">
	    {% for message in messages %}
	    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
	    {% endfor %}
	</ul>
{% endif %}

src/templates/post_detail.html
{% extends "base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}

{% block head_title %}
    {{ instance.title }} |  {{ block.super }}
{% endblock head_title %}

    {% block content %}
    <div class="col-xs-12 col-xs-offset-0 col-sm-9 col-sm-offset-1 col-md-6 col-md-offset-3 post-detail-item">
    <div>

    </div>
        <div> 
         <h1>{{ instance.title }} 
        {% if instance.draft %} <small>draft</small>{% endif %}
            <small>{{ instance.publish }} </small></h1>
        </div>
        <div>
            <p>Read time:  {% if instance.read_time <= 01 %} < 1 minute {% else %}{{ instance.read_time }} minutes {% endif %}</p>
            <p>{% include "messages_display.html" %}</p>
            
        </div>

        <div>
            {% if instance.image %}
                <img src="{{ instance.image.url }}" class="img-responsive">
            {% endif %}            
        </div>

        <p>
            {% if instance.user.get_full_name %}
                Author: {{ instance.user.get_full_name }}
            {% endif %}
        </p>
        <p><div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-layout="button_count" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div></p>
        <hr>
        <p class="content-markdown ">
            {{ instance.get_markdown }}
        </p>
        <p>
            <a href="{% url 'posts:list' %}" class="btn btn-default" role="button">Posts</a>
            {% if instance.user == request.user %}
                <a href="{% url 'posts:update' instance.slug %}" class="btn btn-default" role="button">Update</a>
            {% endif %}
        </p>
            
        <hr>
        {% if request.user.is_authenticated %}
        <form method="POST" action="">
        {% csrf_token %}
         {{ comment_form|crispy }}
            <input type="submit" value="Comment post" class="btn btn-default">
        </form>
        {% else %}
        <p>You must login to comment</p>
        {% endif %}
        <hr>

        <div>
            <p class="lead">Comments</p>

        {% for comment in comments %}
            <blockquote class="blockquote">
              <p class="mb-0">{{ comment.content }}</p>
              <footer class="blockquote-footer">{{ comment.user }} | {{ comment.timestamp|timesince }} ago | {% if comment.children.count > 1 %} {{ comment.children.count }} comments | {% endif %} {% if comment.children.count == 1 %} 1 comment | {% endif %}
            {% if instance.user == request.user %}
            <a href="{{ comment.get_delete_url }}" >Delete a comment |</a>
            {% endif %}
              <a href="#" class="comment-reply-btn">Reply</a> | <a href="{{ comment.get_absolute_url }}" >Thread</a></footer>
            <div class="comment-reply">
                {% for child_comment in comment.children %}
                <blockquote class="blockquote">
                  <p class="mb-0">{{ child_comment.content }}</p>
                  <footer class="blockquote-footer">{{ child_comment.user }} | {{ child_comment.timestamp|timesince }} ago</footer>
                </blockquote>
                {% endfor %}
                <form method="POST" action="">
                {% csrf_token %}
                 {{ comment_form|crispy }}
                    <input type="hidden" name="parent_id" value="{{ comment.id }}" >
                    <input type="submit" value="Reply" class="btn btn-default">
                </form>
            </div>
            </blockquote>
    {% endfor %}
        </div>

<!-- facebook comments -->
        <!-- <div class="row">
                <div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-layout="button_count" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>
                <div class="fb-comments" data-href="{{ request.build_absolute_uri }}" data-numposts="5"></div>
        </div> -->
        
    </div>
    {% endblock content %}

src/templates/post_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_title %}FORM | {{ block.super }}{% endblock head_title %}
{% block head_extra %}{{ form.media }}{% endblock head_extra %}
	
{% block content %} 
<div class="col-md-6" id="preview" >
<h1>Preview</h1>
<div class="content-preview post-detail-item ">
	<h3 id="preview-title"></h3>
	<p id="preview-content" ></p>
</div>
</div>

<div class="col-md-6">

<h1>PostForm</h1>
<form method="POST" action="" enctype="multipart/form-data">
{% csrf_token %}	
{{ form|crispy }}
<input type="submit" class="btn btn-default"  value="Create Post">
</form>
</div>

{% endblock content %}

src/templates/post_list.html
{% extends "base.html" %}

{% block head_title %}
{{ block.super }}
{% endblock head_title %}


{% block content %}
	<div class="col-xs-12 col-xs-offset-0 col-sm-9 col-sm-offset-1 col-md-6 col-md-offset-3 ">
    <h1>Posts</h1>
    <form method="get" action="" class="row">
    <div class="col-sm-6">
        <div class="input-group">
            <input class="form-control" type="text" name="q" placeholder="Search posts" value="{{ request.GET.q }}">
            <span class="input-group-btn">
                <!-- <input class="btn btn-default"  type="submit" value="search"> -->
                <button type="submit" class="btn btn-default" >Search <i class="fa fa-search"></i></button>
            </span>
        </div>
    </div>
        
    </form>
		<p>{% include "messages_display.html" %}</p>
		{% for obj in object_list %}
	    <div class="thumbnail">
	      <!-- <img src="..." alt="..."> -->
	      <div class="caption post-detail-item">
		      <h4>{% if obj.draft %} <span >For the staff: in draft yet. </span> {% endif %}
		      {% if obj.publish > today %} <span > Future publish. </span> {% endif %}
		      </h4>
		        <h3><a href="{{ obj.get_absolute_url }}" >{{ obj.title }} </a>
		        <small>{{ obj.publish }}</small> </h3>
		        {% if obj.image%}
					<img src="{{ obj.image.url }}" class="img-responsive">
				{% endif %}
		        <p class="content-markdown">{{ obj.get_markdown|truncatewords_html:10 }}</p>
		        <p><a href="{{ obj.get_absolute_url }}" class="btn btn-primary" role="button">View</a></p>
	      </div>
	    </div>
	      <hr>
		{% endfor %}
		<div class="pagination">
	    <span class="step-links">
	        {% if object_list.has_previous %}
	            <a href="?page={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
	        {% endif %}

	        <span class="current">
	            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
	        </span>

	        {% if object_list.has_next %}
	            <a href="?page={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
	        {% endif %}
	    </span>
		</div>
	</div>
{% endblock content %}